### ISSUE TITLE
Search for bugs with a non-default assigned_to field, instead of ASSIGNED

### ISSUE THREAD

**Issue by jdm** [noliverio/Inactive-mentored-bug-tracker#1]
Unfortunately Bugzilla does not enforce setting the bug status to ASSIGNED when a bug's assignee is changed, so we need to be more deliberate about the check.

**Comment by noliverio** [comment]
Thanks, I hadn't realized that. The search now looks for bugs that are not assigned to the default assignee. Fixed by commit 8dd138e8d48876df7fcdb1fea0c422ba0987e0ca
