### ISSUE TITLE
Try sending JSON data in search_bugs instead of adding query variables

### ISSUE THREAD

**Issue by jdm** [noliverio/Inactive-mentored-bug-tracker#5]
Similar to https://github.com/jdm/bugsahoy/blob/master/magic.js#L533. I think the resulting code will be easier to follow. There should be no need for the list_id, either.

**Comment by noliverio** [comment]
Looking at the code i agree it is much more clear what is being done this way, fixed by commit 8a6f7d47640ab67ef076199893610d11f184f926
