### ISSUE TITLE
Ensure we're finding all bugs that were last changed >N days ago

### ISSUE THREAD

**Issue by jdm** [noliverio/Inactive-mentored-bug-tracker#6]
From reading the code now, it looks like we're searching for bugs that were last modified exactly N days ago. That seems like it will be easy to miss bugs if we don't end up running the script every day.

**Comment by noliverio** [comment]
I've been thinking about this problem. I worried that we would run into a problem with scale if I had the script search for days elapsed greater than N, but I just checked and the api only returns about 2000 bugs for days elapsed greater than N. This will be fixed in the next commit

**Comment by jdm** [comment]
Wait, do we really have 2000 mentored bugs with assignees that have been inactive for >N days?

**Comment by jdm** [comment]
Oh, maybe we should be limiting to bugs that do not have a status of RESOLVED?

**Comment by noliverio** [comment]
Right I just added that, by picking just unresolved bugs it brings us down to just under 500.
